# Generated by Django 6.0.4 on 2026-05-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='beautyspot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.beautyspot'),
        ),
    ]
