# Generated by Django 6.0.4 on 2026-05-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cart_beautyspot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Product review', 'verbose_name_plural': 'Product reviews'},
        ),
    ]
